### ISSUE TITLE
[BUG]: Battling doesnt work.

### ISSUE THREAD

**Issue by Trizzle1775** [TheHunterManX/GBA-PK-multiplayer#34] opened 2023-02-06 04:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

When me and my friend try to battle each other it says that nothing happened? can this be fixed?

### Steps To Reproduce

.

**Comment by televisionia** [comment] 2023-02-06 06:29
Just a quick note before I explain: Please check other issues to see if your problem has already been answered. (your issue is a duplicate of #19 and #2)

Battles have not been implemented yet, they will be added in the Alpha 4 update.

**Comment by TheHunterManX** [comment] 2024-08-16 22:32
Yep Alpha 4

**Closed by TheHunterManX** 2024-08-16 22:32 UTC
Labels: bug
